### ISSUE TITLE
Lambda server-function is unstable on AWS

### ISSUE THREAD

**Issue by ldlinhlxag** [sst/open-next#189]
We're using open-next to build nextjs app.
We also use next-intl and next-auth in our project.
Refer: https://github.com/amannn/next-intl/tree/main/examples/example-next-13-next-auth
Deploy on AWS Services: CloudFront, S3, Lambda.
After deploy, all features works fine.
But our production is unstable.
Sometime, it cannot show homepage. Only return blank page with null text.
Check AWS CloudWatch log, it shows error:

`2023-08-28T02:48:05.865Z	b263eb20-4f6d-4e01-bb6d-3a2751e41411	ERROR	TypeError: Cannot read properties of null (reading 'useCallback')
    at Object.useCallback (/var/task/node_modules/react/cjs/react.development.js:1646:21)
    at InsertedHTML (/var/task/node_modules/next/dist/server/app-render/app-render.js:861:52)
    at Je (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:121:272)
    at Z (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:128:91)
    at Ee (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:137:422)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:150:403)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)`

I created global-error and errors for each routing. It not catch anything.
When server-function return null with http status code is 200 ?

**Comment by khuezy** [comment]
What nextjs version are you using? Be sure to stick to 13.4.12; see issues and PR for details regarding all the issues.

**Comment by conico974** [comment]
Yeah there is an issue right now with middleware rewrite and app dir.
For it to work correctly you'll need both this PR https://github.com/sst/open-next/pull/169 and next 13.4.13+.

In the meantime you could try adding a catch all routes at the root, it might fix the issue

**Comment by khuezy** [comment]
We're trying to get all the 13.4.13 issues merged this week and get out a `rc` release some time next week. It might take a couple more weeks if we find other issues.

**Comment by ldlinhlxag** [comment]
Thank you for telling me.
