### ISSUE TITLE
Permissions-Policy header in next.config.mjs causes Missing pattern at 7 TypeError

### ISSUE THREAD

**Issue by grefrit** [sst/open-next#332]
Try to add Permissions-Policy to next.config.mjs with `camera=(), microphone=(), geolocation=()` value. You will see
```
Invoke Error    {
  "errorType": "TypeError",
  "errorMessage": "Missing pattern at 7",
  "stack": [
    "TypeError: Missing pattern at 7",
    "    at n8e (file:///var/task/index.mjs:42:242011)",
    "    at aO (file:///var/task/index.mjs:42:242248)",
    "    at r8e (file:///var/task/index.mjs:42:243214)",
    "    at file:///var/task/index.mjs:50:3232",
    "    at Array.forEach (<anonymous>)",
    "    at Y7 (file:///var/task/index.mjs:50:3158)",
    "    at nee (file:///var/task/index.mjs:50:10193)",
    "    at iee (file:///var/task/index.mjs:50:12077)",
    "    at Runtime.handler (file:///var/task/server-index.mjs:15:10)"
  ]
}
```

is SST console

**Comment by conico974** [comment]
This works in V3
