### ISSUE TITLE
[BUG] Error on Warmer function

### ISSUE THREAD

**Issue by pinarruiz** [sst/open-next#420]
I am getting this error on my warmer function, both the cron and a test event throw the same error:

```json
{
  "errorType": "SyntaxError",
  "errorMessage": "\"undefined\" is not valid JSON",
  "trace": [
    "SyntaxError: \"undefined\" is not valid JSON",
    "    at JSON.parse (<anonymous>)",
    "    at Object.invoke (file:///var/task/warmer-function/index.mjs:25:220642)",
    "    at async f1 (file:///var/task/warmer-function/index.mjs:25:221498)",
    "    at async Runtime.handler (file:///var/task/warmer-function/index.mjs:2:1818)"
  ]
}
```

The project its pretty simple, so if needed I will create a public copy. If any more info is needed i will provide it.
Using `yarn@1.22.21` and `node` `v21.5.0`.

`package.json`:
```json
{
  "dependencies": {
    "@aws-sdk/client-cloudfront": "3.577.0",
    "moment": "2.30.1",
    "next": "14.2.3",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "20.12.12",
    "@types/react": "18.3.2",
    "@types/react-dom": "18.3.0",
    "eslint": "8.57.0",
    "eslint-config-next": "14.2.3",
    "open-next": "3.0.1",
    "serverless": "3.38.0",
    "serverless-iam-roles-per-function": "3.2.0",
    "serverless-plugin-lambda-insights": "2.0.0",
    "serverless-prune-plugin": "2.0.2",
    "serverless-s3-sync": "3.3.0",
    "typescript": "5.4.5"
  }
}
```

**Comment by conico974** [comment]
@pinarruiz Did you set the `WARM_PARAMS` env ? https://open-next.js.org/inner_workings/components/warmer#invoke-function
FYI `function` here refers to the function name

**Comment by pinarruiz** [comment]
@conico974 ohh i was going with the `FUNCTION_NAME` and `CONCURRENCY` env vars as stated by the docs https://github.com/sst/open-next/blob/65f7a6032d0dba552084becae50da9cf22145e09/docs/pages/v2/advanced/architecture.mdx#warmer-function

**Comment by pinarruiz** [comment]
It was just that, thanks for the help :smile:
