### ISSUE TITLE
Next config redirects is not working correctly on Next 12

### ISSUE THREAD

**Issue by tsurumeso** [sst/open-next#458]
Next.js version: 12.3.4
OpenNext version: 3.0.6

Hi, I am running a server function on Lambda@Edge and setting a redirect in `next.config.js` as follows.
```
# next.config.js
const nextConfig = {
  ...
  redirects: async () => {
    return [
      {
        source: '/foo',
        destination: '/bar',
        permanent: true,
      },
    ];
  },
};
```
Then, accessing `/foo` returns status code 500 and the Lambda outputs the following logs to CloudWatch.
```
ERROR	TypeError: res.redirect is not a function
    at Object.fn (/var/task/node_modules/next/dist/server/server-route-utils.js:111:17)
    at Router.execute (/var/task/node_modules/next/dist/server/router.js:252:48)
    at NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:365:47)
    at NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:303:31)
    at /var/task/node_modules/next/dist/server/next-server.js:839:20
ERROR	NextJS request failed. TypeError: res.body is not a function
    at NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:314:17)
```
I wonder if this is due to using Next 12 since the redirects seem to work correctly in the E2E test of this project.

**Comment by conico974** [comment]
I see, it looks like we'll have to implement these 2 methods in `OpenNextNodeResponse` as well.
