### ISSUE TITLE
The basePath breaks the OpenNext build.

### ISSUE THREAD

**Issue by doc-sultan** [sst/open-next#55]
By adding `basePath` to `next.config.js` breaks the build process.

I'm using the `sst: 2.1.23` & `next: 13.2.3`

```sh
Bundling server function...
Bundling image optimization function...
Bundling middleware edge function...
file:///mac/.npm/_npx/a94ce00fc9d9ef90/node_modules/open-next/dist/build.js:196
    const src = buildOutput.output[middlewareName].files["index.js"].data;
                                                   ^
TypeError: Cannot read properties of undefined (reading 'files')
    at createMiddlewareBundle (file:///mac/.npm/_npx/a94ce00fc9d9ef90/node_modules/open-next/dist/build.js:196:52)
    at build (file:///mac/.npm/_npx/a94ce00fc9d9ef90/node_modules/open-next/dist/build.js:25:5)
Error: There was a problem building the "Site" StaticSite.

Trace: Error: There was a problem building the "Site" StaticSite.
    at NextjsSite.runBuild (file:///mac/nextjs-v13/node_modules/sst/constructs/SsrSite.js:252:19)
    at NextjsSite.buildApp (file:///mac/nextjs-v13/node_modules/sst/constructs/SsrSite.js:215:18)
    at new SsrSite (file:///mac/nextjs-v13/node_modules/sst/constructs/SsrSite.js:75:14)
    at new NextjsSite (file:///mac/nextjs-v13/node_modules/sst/constructs/NextjsSite.js:28:9)
    at EmptyStack.nextjs (/mac/nextjs-v13/sst.config.ts:9:16)
    at stack (file:///mac/nextjs-v13/node_modules/sst/constructs/FunctionalStack.js:20:35)
    at App.stack (file:///mac/nextjs-v13/node_modules/sst/constructs/App.js:489:16)
    at Object.stacks (/mac/nextjs-v13/sst.config.ts:28:9)
    at Module.synth (file:///mac/nextjs-v13/node_modules/sst/stacks/synth.js:54:20)
    at async Object.handler (file:///mac/nextjs-v13/node_modules/sst/cli/commands/build.js:9:20)
    at process.<anonymous> (file:///mac/nextjs-v13/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:539:35)
    at process.emit (node:domain:475:12)
    at process._fatalException (node:internal/process/execution:167:25)
    at processPromiseRejections (node:internal/process/promises:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

**Comment by dmn-bernard** [comment]
Hello, I'm having the same issue as well. We recently upgraded to nextJS 13, and left serverless-next for SST with open-next because serverless-next was breaking on our deployments. We were also using the `basePath` feature in our project and I get the same error as above, unless I remove this `basePath`.

**Comment by khuezy** [comment]
Hi, it's been awhile since but this is 75% SST, we need to set the `basePath` to the distribution and S3 asset paths. I don't think open-next needs to update much (or nothing at all).

**Comment by conico974** [comment]
Feel free to reopen if you still have issues
