### ISSUE TITLE
Error while being used as a child process

### ISSUE THREAD

**Issue by ibraelillo** [sst/open-next#6]
Hello guys, 

I'm facing this issue while using the `npx open-next build` as a child process:

My code:
```typescript
// ... 

console.log(chalk.green(`Code is located at: ${sitePath}`))

spawnSync('npx', ['open-next', 'build'], {
    cwd: sitePath,
    stdio: 'inherit',
    env: {
        ...process.env,
        NODE_OPTIONS: '--preserve-symlinks'
    }
})
```

```bash
Warning: Detected "engines": { "node": ">=16" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
Detected `pnpm-lock.yaml` generated by pnpm 7...
WARNING: You should not upload the `.next` directory.
Installing dependencies...
Scope: all 17 workspace projects

../config postinstall$ yarn build
../config postinstall: yarn run v1.22.19
../config postinstall: warning package.json: No license field
../config postinstall: $ tsup
../config postinstall: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ibra/accor/astore/node_modules/.pnpm/node_modules/strip-final-newline/index.js from /home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/execa/index.js not supported.
../config postinstall: Instead change the require of /home/ibra/accor/astore/node_modules/.pnpm/node_modules/strip-final-newline/index.js in /home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/execa/index.js to a dynamic import() which is available in all CommonJS modules.
../config postinstall:     at Object.<anonymous> (/home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/execa/index.js:5:27)
../config postinstall:     at Object.<anonymous> (/home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/tsup/dist/index.js:1189:14)
../config postinstall:     at /home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/tsup/dist/chunk-PDM6VDW3.js:170:58
../config postinstall:     at async CAC.<anonymous> (/home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/tsup/dist/chunk-PDM6VDW3.js:170:23)
../config postinstall:     at async main (/home/ibra/accor/astore/node_modules/.pnpm/tsup@6.5.0_typescript@4.9.3/node_modules/tsup/dist/chunk-PDM6VDW3.js:223:3)
../config postinstall: error Command failed with exit code 1.
../config postinstall: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
../config postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
/home/ibra/accor/astore/node_modules/.pnpm/open-next@0.1.0/node_modules/@vercel/build-utils/dist/index.js:30916
            reject(new errors_1.NowBuildError({
                   ^

NowBuildError: Command "pnpm install" exited with 1
    at ChildProcess.<anonymous> (/home/ibra/accor/astore/node_modules/.pnpm/open-next@0.1.0/node_modules/@vercel/build-utils/dist/index.js:30916:20)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  hideStackTrace: true,
  code: 'BUILD_UTILS_SPAWN_1',
  link: undefined,
  action: undefined
}

```

**Comment by fwang** [comment]
Hey @ibraelillo, we recently added support for pnpm and monorepo. I'm curious if this issue might've been fixed.

Let me know if you are still having this issue.

**Comment by khuezy** [comment]
Please reopen if not fixed.
